[package]
name = "sc-cap"
description = "Modern, high-performance screen capture library for Rust. Cross-platform."
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = [
	"nemurubaka <cijiugechu@gmail.com>",
	"Siddharth <siddharth99c@gmail.com>",
	"Pranav <pranav2000joglekar@gmail.com>",
]
readme = "README.md"
repository = "https://github.com/cijiugechu/sc-cap"
documentation = "https://docs.rs/sc-cap"
keywords = ["screen", "recording", "video", "capture", "media"]
categories = ["graphics", "multimedia", "multimedia::video"]

[dependencies]
futures = "0.3"
sysinfo = "0.37"
thiserror = "2"
wgpu = "27"
wgpu-hal = "27"

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-capture = "1.5.0"
windows = { version = "0.58", features = [
	"Win32_Foundation",
	"Win32_Graphics_Gdi",
	"Win32_UI_HiDpi",
	"Win32_UI_WindowsAndMessaging",
	"Win32_System_Performance",
] }
cpal = "0.15.3"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-core-foundation = "0.3"
objc2-core-graphics = "0.3"
objc2-foundation = "0.3"
cidre = { version = "0.10.1", default-features = false, features = [
	"async",
	"av",
	"sc",
	"dispatch",
	"macos_13_0",
	"mtl",
] }
core-foundation = "0.9"
metal = "0.32"

[target.'cfg(target_os = "linux")'.dependencies]
pipewire = "0.8.0"
dbus = "0.9.7"
rand = "0.8.5"
